stages:
    - build
    - test
    
gcc:
  stage: build
  before_script:
    - echo "LAMA Version:" && expr `git --git-dir=${SCAI_ROOT}/../.git/ log -1 --pretty=%h`
  script:
    - echo "g++ Version:" && g++ --version
    - cd src/ && make install CC=g++ CFLAGS="-std=c++11 -fopenmp -Wall -Wextra -Werror"
  artifacts:
    when: on_success
    expire_in: 10 min
    paths:
      - bin/

openmp-gcc:
  stage: test
  dependencies:
    - gcc
  script:
    - DYLD_LIBRARY_PATH=${SCAI_ROOT}/lib/:${DYLD_LIBRARY_PATH}
    - LD_LIBRARY_PATH=${SCAI_ROOT}/lib:${LD_LIBRARY_PATH}
    - OMP_NUM_THREADS=4
    - cd par/
    - ./../bin/FDSimulation "input/Config_CI.txt"
    - cd seismograms && gnuplot seismogram.gnuplot
  artifacts:
    when: on_success
    expire_in: 30 min
    name: "openmp-gcc"
    paths:
      - par/seismograms/seismogram.png

openmpi-gcc:
  stage: test
  dependencies:
    - gcc
  script:
    - DYLD_LIBRARY_PATH=${SCAI_ROOT}/lib/:${DYLD_LIBRARY_PATH}
    - LD_LIBRARY_PATH=${SCAI_ROOT}/lib:${LD_LIBRARY_PATH}
    - OMP_NUM_THREADS=1
    - cd par/
    - mpirun -np 4 ./../bin/FDSimulation "input/Config_CI.txt"
    - md5sum seismograms/seismogram.mtx
    - cd seismograms && gnuplot seismogram.gnuplot
  artifacts:
    when: on_success
    expire_in: 30 min
    name: "openmpi-gcc"
    paths:
      - par/seismograms/seismogram.png