stages:
    - build
    - test
    
gcc:
  stage: build
  before_script:
    - echo "LAMA Version:" && expr `git --git-dir=${SCAI_ROOT}/../.git/ log -1 --pretty=%h`
  script:
    - echo "g++ Version:" && g++ --version
    - cd src/ && make install CC=g++ CFLAGS="-std=c++11 -fopenmp -Wall -Wextra -Werror"
  artifacts:
    when: on_success
    expire_in: 10 min
    paths:
      - bin/

acoustic3D-gcc:
  stage: test
  dependencies:
    - gcc
  script:
    - DYLD_LIBRARY_PATH=${SCAI_ROOT}/lib/:${DYLD_LIBRARY_PATH}
    - LD_LIBRARY_PATH=${SCAI_ROOT}/lib:${LD_LIBRARY_PATH}
    - OMP_NUM_THREADS=2
    - cd par/
    - mpirun -np 2 ./../bin/SOFI3Dacoustic "ci/configuration_ci.acoustic.txt"
    - ./../bin/Tests/Test_SOFI3Dacoustic "ci/configuration_ci.acoustic.txt"

elastic3D-gcc:
  stage: test
  dependencies:
    - gcc
  script:
    - DYLD_LIBRARY_PATH=${SCAI_ROOT}/lib/:${DYLD_LIBRARY_PATH}
    - LD_LIBRARY_PATH=${SCAI_ROOT}/lib:${LD_LIBRARY_PATH}
    - OMP_NUM_THREADS=2
    - cd par/
    - mpirun -np 2 ./../bin/SOFI3Delastic "ci/configuration_ci.elastic.txt"
    - ./../bin/Tests/Test_SOFI3Delastic "ci/configuration_ci.elastic.txt"