stages:
    - build
    - unittest
    - simulation
    

gcc:
  stage: build
  before_script:
    - SCAI_ROOT=/home/tmetz/lama/build_g++-8
    - echo "LAMA Version:" && file ${SCAI_ROOT}/lib/libscai_lama.so | sed 's/.*libscai_lama\.so\.\([0-9]*\.[0-9]*\.[0.9]*\).*/\1/g'
  script:
    - echo "g++ Version:" && g++-8 --version
    - cd build/ && make CXX=g++-8 -j 8 prog && make CXX=g++-8 -j 8 utest && make CXX=g++-8 itest && make CXX=g++-8 model
  artifacts:
    when: on_success
    expire_in: 30 min
    paths:
      - build/bin/


unittest-gcc:
  stage: unittest
  script:
    - cd par/
    - ./../build/bin/Test_unit


acoustic2D-gcc:
  stage: simulation
  script:
    - OMP_NUM_THREADS=2
    - cd par/
    - mpirun -np 4 ./../build/bin/SOFI "ci/configuration_ci.2D.acoustic.txt"
    - ./../build/bin/Test_integration "ci/configuration_ci.2D.acoustic.txt"

acoustic3D-gcc:
  stage: simulation
  script:
    - OMP_NUM_THREADS=2
    - cd par/
    - ./../build/bin/tools/TwoLayer "ci/configuration_ci.3D.acoustic.txt"
    - mpirun -np 4 ./../build/bin/SOFI "ci/configuration_ci.3D.acoustic.txt"
    - ./../build/bin/Test_integration "ci/configuration_ci.3D.acoustic.txt"


elastic2D-gcc:
  stage: simulation
  script:
    - OMP_NUM_THREADS=2
    - cd par/
    - ./../build/bin/tools/TwoLayer "ci/configuration_ci.2D.elastic.txt"
    - mpirun -np 4 ./../build/bin/SOFI "ci/configuration_ci.2D.elastic.txt"
    - ./../build/bin/Test_integration "ci/configuration_ci.2D.elastic.txt"

elastic3D-gcc:
  stage: simulation
  script:
    - OMP_NUM_THREADS=2
    - cd par/
    - ./../build/bin/tools/TwoLayer "ci/configuration_ci.3D.elastic.txt"
    - mpirun -np 4 ./../build/bin/SOFI "ci/configuration_ci.3D.elastic.txt"
    - ./../build/bin/Test_integration "ci/configuration_ci.3D.elastic.txt"


visco2D-gcc:
  stage: simulation
  script:
    - OMP_NUM_THREADS=2
    - cd par/
    - ./../build/bin/tools/TwoLayer "ci/configuration_ci.2D.visco.txt"
    - mpirun -np 4 ./../build/bin/SOFI "ci/configuration_ci.2D.visco.txt"
    - ./../build/bin/Test_integration "ci/configuration_ci.2D.visco.txt"

visco3D-gcc:
  stage: simulation
  script:
    - OMP_NUM_THREADS=2
    - cd par/
    - ./../build/bin/tools/TwoLayer "ci/configuration_ci.3D.visco.txt"
    - mpirun -np 4 ./../build/bin/SOFI "ci/configuration_ci.3D.visco.txt"
    - ./../build/bin/Test_integration "ci/configuration_ci.3D.visco.txt"

sh2D-gcc:
  stage: simulation
  script:
    - OMP_NUM_THREADS=2
    - cd par/
    - mpirun -np 4 ./../build/bin/SOFI "ci/configuration_ci.2D.sh.txt"
    - ./../build/bin/Test_integration "ci/configuration_ci.2D.sh.txt"

